### ISSUE TITLE
Logger without handlers

### ISSUE THREAD

**Issue by jcalderin** [eXamadeus/godaddypy#7]
When a log level is passed to the client (e.g. logging.DEBUG) the handler is not found raising:

`  No handlers could be found for logger "GoDaddyPy.Client"`

Fixing it in Client.py module
```
   # Logging setup
        logging.basicConfig()
        self.logger = logging.getLogger('GoDaddyPy.Client')
```

**Comment by eXamadeus** [comment]
This is expected behavior and is notifying consumers of the library that they attempting to use logging without first configuring handlers.

See https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library for reasoning behind this decision.

To solve this, call `logging.basicConfig()` OR simply use logging in production mode and set `logging.raiseExceptions = False` in your calling script.  HOWEVER, using the second method means that logging won't occur in the library because the logging module was imported but never configured.  This falls outside of the wheelhouse of what I believe this library should do.

**Comment by eXamadeus** [comment]
To summarize, this is simply my opinion on the matter and I may very well be objectively wrong.  I simply believe it is important to not do "magic" behind the scenes in a library and I don't want to contribute to peoples misunderstandings of how the logging system in python works.
